apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd
  namespace: techdebt
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd
  namespace: techdebt
rules:
  - apiGroups: ["", "apps", "batch", "extensions", "networking.k8s.io"]
    resources: ["deployments", "services", "replicasets", "pods", "jobs", "cronjobs", "ingresses"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd
  namespace: techdebt
subjects:
  - kind: ServiceAccount
    name: cicd
    namespace: techdebt
roleRef:
  kind: Role
  name: cicd
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
metadata:
  name: cicd
  namespace: component-labs
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd
  namespace: component-labs
rules:
  - apiGroups: ["", "apps", "batch", "extensions", "networking.k8s.io"]
    resources: ["deployments", "services", "replicasets", "pods", "jobs", "cronjobs", "ingresses"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd
  namespace: component-labs
subjects:
  - kind: ServiceAccount
    name: cicd
    namespace: component-labs
roleRef:
  kind: Role
  name: cicd
  apiGroup: rbac.authorization.k8s.io
